# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine:
        enabled: true
    environment:
        COMPOSE_FILE: docker-compose.development.yml
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/caches/images.tar
      - run:
          name: docker load
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 5
      - run:
          name: "before_test: setup db"
          command: docker-compose run --rm web rails db:create
      - run:
          name: "before_test: create table"
          command: docker-compose run --rm web ridgepole -c config/database.yml -E development --apply -f db/schemas/Schemafile
      - run:
          name: test
          command: docker-compose run web rspec
      - run:
          command: mkdir -p ~/caches
          name: mkdir -p ~/caches
      - run:
          command: |
            if [[ ! -e ~/caches/images.tar ]]; then
              docker save -o ~/caches/images.tar $(docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}")
            fi
          name: docker save
      - save_cache:
          key: v1-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/caches/images.tar
      - run:
          name: docker-compose down
          command: docker-compose down
